image: "alpine:latest"

stages:
  - build
  - test
  - alpha
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: morecreepsrevival-builds

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - build/libs/

build:
  stage: build
  before_script:
    - apk add --no-cache build-base openjdk8 gradle bash
  script:
    - chmod +x gradlew
    - ./gradlew build
  only:
    - alpha
    - master

test:
  stage: test
  script:
    - echo No tests are currently enabled.
  only:
    - alpha
    - master

alpha:
  stage: alpha
  before_script:
    - apk add --no-cache python3 bash
    - pip3 install --upgrade pip awscli
  script:
    - chmod +x upload_alpha_to_s3.sh
    - ./upload_alpha_to_s3.sh
  only:
    - alpha

release:
  stage: deploy
  before_script:
    - apk add --no-cache python3 bash
    - pip3 install --upgrade pip awscli
  script:
    - chmod +x upload_release_to_s3.sh
    - ./upload_release_to_s3.sh
  only:
    - master